<?php
/**
 * Author: Pavel Zarubov <zara@fu2re.ru>
 * Date: 20.05.2014
 * Time: 10:44
 */
?>
<div class="share-buttons">
    <span class='st_sharethis_hcount' displayText='ShareThis'></span>
    <span class='st_facebook_hcount' displayText='Facebook'></span>
    <span class='st_twitter_hcount' displayText='Tweet'></span>
    <span class='st_linkedin_hcount' displayText='LinkedIn'></span>
    <span class='st_googleplus_hcount' displayText='Google +'></span>
    <span class='st_pinterest_hcount' displayText='Pinterest'></span>
</div>
