<?php

namespace ExprAs\Rest\Hydrator;

use Doctrine\Laminas\Hydrator\DoctrineObject as DoctrineHydrator;
use Doctrine\Persistence\ObjectManager;
use ExprAs\Rest\Hydrator\Configurator\RestHydratorConfiguratorInterface;

class RestHydrator extends DoctrineHydrator
{
    /**
     * @var array | RestHydratorConfiguratorInterface[] 
     */
    protected array $_configurators = [];

    /**
     * @return array | RestHydratorConfiguratorInterface[]
     */
    public function getConfigurators(): array
    {
        return $this->_configurators;
    }

    public function setConfigurators(array $configurators): void
    {
        $this->_configurators = $configurators;
    }

    /**
     * @param array $configurators
     */
    public function addConfigurator($configurator): void
    {
        $this->_configurators[] = $configurator;
    }

    /**
     * @param $type
     *
     * @return RestHydratorConfiguratorInterface|null
     */
    public function getConfigurator($type): ?RestHydratorConfiguratorInterface
    {
        foreach ($this->getConfigurators() as $_configurator) {
            if ($_configurator instanceof $type) {
                return $_configurator;
            }
        }

        return null;
    }

    /**
     * @return ObjectManager
     */
    public function getObjectManager(): ObjectManager
    {
        return $this->objectManager;
    }

    /**
     * Prepare the hydrator by configurators
     *
     * @param  object $object
     * @return void
     */
    #[\Override]
    protected function prepare($object): void
    {
        foreach ($this->getConfigurators() as $_configurator) {
            $_configurator->canConfigureStrategies($this, $object) && $_configurator->configureStrategies($this, $object);
            $_configurator->canConfigureFilters($this, $object) && $_configurator->configureFilters($this, $object);
        }
        parent::prepare($object);
    }

    #[\Override]
    protected function handleTypeConversions(mixed $value, ?string $typeOfField)
    {
        switch ($typeOfField) {
        case 'json':
        case 'array':
        case 'simple_array':
            if (!$value) {
                $value = [];
            }
            break;
        }
        return parent::handleTypeConversions($value, $typeOfField); // TODO: Change the autogenerated stub
    }
}
