<i class="alert-link adv-ph yandex_ads_rendered yad-loaded adsbygoogle yandex_ads_wrap text-center fullscreen-mobile-yad-overlay timer">
    <span class="close"></span>
</i>

<section class="dict-word-usage">
    <div class="bg-info">
        <h4>Примеры употребления слова кувандык в литературе.</h4>

        <p>Через <a href="/wd/%D0%BA%D1%83%D0%B2%D0%B0%D0%BD%D0%B4%D1%8B%D0%BA">Кувандык</a> раз в два дня проходят поезда Оренбург-Свердловск и Саратов-Челябинск, а также ежедневный поезд Орск-Москва.</p>
        <p>Уже за Сагарчином, ближе к <a href="/wd/%D0%BA%D1%83%D0%B2%D0%B0%D0%BD%D0%B4%D1%8B%D0%BA">Кувандыку</a>, когда до Оренбурга оставалось рукой подать, впереди показался мост, весь в строительных лесах, -- видимо, в половодье повредило фермы, -- и Дасаев сбавил скорость.</p>
        <p>Можно прервать его и раньше, в деревнях Большое Абишево и Большое Чураево, связанных с <a href="/wd/%D0%BA%D1%83%D0%B2%D0%B0%D0%BD%D0%B4%D1%8B%D0%BA">Кувандыком</a> автобусным сообщением.</p>
        <p class="text-muted text-right">
            <small>Источник: библиотека Максима Мошкова</small>
        </p>
    </div>
</section>
<aside id="sidebar" class="sidebar-offcanvas collapse show"></aside>
<div id="ads_topbar" class="ads-block-horizontal yandex_ads_rendered"></div>